name: Pipeline with approve with PR
concurrency: ci-${{ github.ref }}
on:
  push:
    branches:
      - dev
  pull_request:

env:
  GO_VERSION: "1.17"
  APP_NAME: hey

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: deploy/Dockerfile
          push: false
          tags: ${{ env.APP_NAME }}
          build-args: |
            GO_VERSION=${{ env.GO_VERSION }}
          target: runner
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}.x
      - name: Test
        run: go test ./... -cover
      - name: Test race
        run: go test -race ./... -cover
